package model;

// Generated 08-feb-2017 21:15:10 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Alumnos generated by hbm2java
 */
@Entity
@Table(name = "alumnos", catalog = "biblioteca")
public class Alumnos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8949244982466922816L;
	private Integer registro;
	private String dni;
	private String nombre;
	private String apellido1;
	private String apellido2;

	public Alumnos() {
	}

	public Alumnos(String dni, String nombre, String apellido1, String apellido2) {
		this.dni = dni;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "registro", unique = true, nullable = false)
	public Integer getRegistro() {
		return this.registro;
	}

	public void setRegistro(Integer registro) {
		this.registro = registro;
	}

	@Column(name = "dni", nullable = false, length = 14)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@Column(name = "nombre", nullable = false, length = 26)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido1", nullable = false, length = 21)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "apellido2", nullable = false, length = 21)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

}
